[package]
name = "firewallchecker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "=0.1.12"
packet_rs = "0.4.0"
ipnet = "2.9.0"
csv = "1.3.0"
